---
- name: Incluye el archivo con las variables
  ansible.builtin.include_vars:
    file: vars_main.yml

- name: Borrar viejas llaves de telegraf
  ansible.builtin.file:
    path: "/etc/apt/trusted.gpg.d/{{ item }}"
    state: absent
  loop:
    - influxdata-archive_compat.gpg
    - influxdata-archive_compat.asc

- name: Importar llave
  ansible.builtin.get_url:
    url: "{{ telegraf_url_key }}"
    dest: "{{ telegraf_dest_key }}"
    mode: 0644

- name: Agregar repositorio
  ansible.builtin.apt_repository:
    repo: 'deb [signed-by={{ telegraf_dest_key }}] {{ telegraf_url_repo }}/debian stable main'
    filename: influxdata
    state: present

- name: Instalar influxdb + dependencias
  ansible.builtin.apt:
    name: [ 'influxdb', 'python3-pip' ]
    update_cache: true
    cache_valid_time: 3600

######## no funciona con ansible 2.15.13 asi voy a usar el modulo shell ##########
# - name: Instalar modulo influxdb para python
#   ansible.builtin.pip:
#     name: influxdb
#     executable: pip3
#     break_system_packages: yes
#################################################################################

- name: Instalar módulo influxdb para Python usando shell
  ansible.builtin.shell: |
    pip3 install influxdb --break-system-packages
  args:
    executable: /bin/bash

- name: reiniciar influxdb # necesito reiniciar el servicio sino no conecta con la db
  ansible.builtin.systemd:
    name: influxdb
    state: restarted
    enabled: yes

- name: Creando db para telegraf
  community.general.influxdb_database:
    hostname: "{{ influxdb_url }}"
    database_name: "{{ influxdb_db }}"
    port: "{{ influxdb_port }}"
    ssl: false
    validate_certs: false

- name: Creando usuario admin en "{{ influxdb_db }}"
  community.general.influxdb_user:
    user_name: "{{ influxdb_user }}"
    user_password: "{{ influxdb_pass }}"
    hostname: "{{ influxdb_url }}"
    admin: true


