---
- name: recargar prometheus
  ansible.builtin.systemd:
    name: prometheus
    state: restarted
    enabled: yes
  listen: servicios_prometheus

- name: recargar telegraf
  ansible.builtin.systemd:
    daemon_reload: true
  listen: servicios_telegraf

- name: reiniciar telegraf
  ansible.builtin.systemd:
    name: telegraf
    state: restarted
    enabled: yes
  listen: servicios_telegraf

- name: reiniciar influxdb
  ansible.builtin.systemd:
    name: influxdb
    state: restarted
    enabled: yes
  listen: servicios_influxdb