---
- name: Incluye el archivo con las variables
  ansible.builtin.include_vars:
    file: vars_main.yml

- name: Borrar viejas llaves de telegraf
  ansible.builtin.file:
    path: "/etc/apt/trusted.gpg.d/{{ item }}"
    state: absent
  loop:
    - influxdata-archive_compat.gpg
    - influxdata-archive_compat.asc

- name: Importar llave
  ansible.builtin.get_url:
    url: "{{ telegraf_url_key }}"
    dest: "{{ telegraf_dest_key }}"
    mode: 0644

- name: Agregar repositorio
  ansible.builtin.apt_repository:
    repo: 'deb [signed-by={{ telegraf_dest_key }}] {{ telegraf_url_repo }}/debian stable main'
    filename: influxdata
    state: present

- name: Instalar aplicaciones
  ansible.builtin.apt:
    name: [ 'telegraf', 'snmp' ]
    update_cache: true

- name: Copiar archivo de configuracion
  template:
    src: files/telegraf.conf.j2
    dest: /etc/telegraf/telegraf.conf
    owner: root
    group: root
    mode: 0644
    backup: yes
  notify: servicios_telegraf


